language: rust
rust:
  - stable
branches:
  only:
    - master
cache:
    - cargo
    - target
install:
  - rustc -Vv
  - cargo -V
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
