language: rust
rust:
  - stable
branches:
  only:
    - master
cache:
    - cargo
    - target
install:
  - travis_wait rustc -Vv
  - travis_wait cargo -V
script:
  - travis_wait cargo build --verbose --all
  - travis_wait cargo test --verbose --all
