[package]
name = "sdmmparser"
version = "0.0.2"

[[bin]]
name = "sdmmparser"
path = "main.rs"

[dependencies]
dreammaker = { path = "../dreammaker" }
serde = "1.0.103"
serde_derive = "1.0.103"
serde_json = "1.0"
