[package]
name = "dmdoc"
homepage = "https://github.com/SpaceManiac/SpacemanDMM/blob/master/crates/dmdoc/README.md"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
dreammaker = { path = "../dreammaker" }
pulldown-cmark = "0.9.6"
walkdir = "2.5.0"
git2.workspace = true
maud = "0.27.0"
foldhash = "0.2.0"

[build-dependencies]
chrono.workspace = true
git2.workspace = true
